openapi: 3.0.3
info:
  title: Loyalty User Management API
  description: 'Loyalty User Management service allows clients to enroll users and their associated accounts into a reward program so that they can avail different promotions or reward benefits provided to their users. Subsequent to enrollment, clients can use this service to retrieve and update user or account information.'
  termsOfService: 'https://developer.mastercard.com/terms-of-use'
  contact:
    name: API Support
    url: 'https://developer.mastercard.com/support'
    email: apisupport@mastercard.com
  license:
    name: Mastercard Developer Support
    url: 'https://developer.mastercard.com/support'
  version: 1.2.0
servers:
  - url: 'https://api.mastercard.com/loyalty/rewards'
    description: Production API
  - url: 'https://sandbox.api.mastercard.com/loyalty/rewards'
    description: Sandbox API
tags:
  - name: User Management
    description: Multiple endpoints are available to perform different User management activities such as <ul><li>New user with account enrollment</li><li>New user enrollment without account</li><li>Update user demographic details</li><li>Fetch user details based on user identifier assigned by Mastercard on enrollment or via user number</li></ul>
  - name: Account Management
    description: Multiple endpoints are available to perform different account management activities such as <ul><li>New account enrollment for an existing user</li><li>Update account status for an existing account</li><li>Fetch user details based on account identifer assigned by Mastercard on enrollment or via account number</li></ul>
paths:
  /users:
    post:
      tags:
        - User Management
      summary: Enroll user and their associated account into a reward program
      description: Enroll user with or without their associated account into a reward program.
      operationId: enrollUser
      x-mastercard-api-encrypted: true
      requestBody:
        $ref: '#/components/requestBodies/UserEnrollRequest'
      responses:
        '201':
          $ref: '#/components/responses/EnrollUserSuccessfully'
        '400':
          $ref: '#/components/responses/EnrollUserInvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /users/searches:
    post:
      tags:
        - User Management
      summary: Allows clients to search and retrieve a user's information.
      description: This endpoint allows clients to search and retrieve a user's information using a combination of the User Number and Company.
      operationId: searchUser
      x-mastercard-api-encrypted: true
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
      requestBody:
        $ref: '#/components/requestBodies/UserSearchRequest'
      responses:
        '200':
          $ref: '#/components/responses/SearchUserSuccessfully'
        '400':
          $ref: '#/components/responses/SearchUserInvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  '/users/{id}':
    get:
      tags:
        - User Management
      summary: Provides clients the ability to retrieve a User's information using the User Id.
      description: This endpoint provides clients the ability to retrieve a User's information using the Mastercard generated User Id.
      operationId: findUser
      x-mastercard-api-encrypted: true
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          $ref: '#/components/responses/FindUserSuccessfully'
        '404':
          $ref: '#/components/responses/UserNotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      tags:
        - User Management
      summary: Provides clients the ability to update existing enrolled user details.
      description: This endpoint provides clients the ability to update existing enrolled user details.<br/> Please note while calling the endpoint make sure that all the attributes are provided in payload with values even if few attributes needs to be updated.
      operationId: updateUser
      x-mastercard-api-encrypted: true
      parameters:
        - $ref: '#/components/parameters/userId'
      requestBody:
        $ref: '#/components/requestBodies/UserUpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/UpdateUserSuccessfully'
        '400':
          $ref: '#/components/responses/UpdateUserInvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /accounts:
    post:
      tags:
        - Account Management
      summary: Allows clients to enroll new accounts for an existing User.
      description: This endpoint allows clients to enroll new accounts for an existing User into a rewards program.
      operationId: enrollAccount
      x-mastercard-api-encrypted: true
      requestBody:
        $ref: '#/components/requestBodies/AccountEnrollRequest'
      responses:
        '201':
          $ref: '#/components/responses/EnrollAccountSuccessfully'
        '400':
          $ref: '#/components/responses/EnrollAccountInvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /accounts/searches:
    post:
      tags:
        - Account Management
      summary: Provides clients the ability to search and retrieve an account's information.
      description: This endpoint provides clients with the ability to search and retrieve an account's information using the combination of Account Number and Company.
      operationId: searchAccount
      x-mastercard-api-encrypted: true
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
      requestBody:
        $ref: '#/components/requestBodies/AccountSearchRequest'
      responses:
        '200':
          $ref: '#/components/responses/SearchAccountSuccessfully'
        '400':
          $ref: '#/components/responses/SearchAccountInvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  '/accounts/{id}':
    get:
      tags:
        - Account Management
      summary: Provides clients the ability to retrieve account's information using the Account Id.
      description: This endpoint provides clients the ability to retrieve account's information using the Mastercard generated Account Id.
      operationId: findAccount
      x-mastercard-api-encrypted: true
      parameters:
        - $ref: '#/components/parameters/accountId'
      responses:
        '200':
          $ref: '#/components/responses/FindAccountSuccessfully'
        '404':
          $ref: '#/components/responses/AccountNotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      tags:
        - Account Management
      summary: Provides clients the ability to update an existing account's status.
      description: This endpoint provides clients the ability to update an existing account's status.
      operationId: updateAccount
      x-mastercard-api-encrypted: true
      parameters:
        - $ref: '#/components/parameters/accountId'
      requestBody:
        $ref: '#/components/requestBodies/AccountUpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/UpdateAccountSuccessfully'
        '400':
          $ref: '#/components/responses/UpdateAccountInvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
components:
  parameters:
    userId:
      name: id
      in: path
      description: User Id
      required: true
      style: simple
      schema:
        type: string
      example: '2a53135b-c1f2-4cec-88a9-b0941304d9d7'
    accountId:
      name: id
      in: path
      description: Account Id
      required: true
      style: simple
      schema:
        type: string
      example: 'd8753780-62d1-4775-9549-8ed92c48c290'
    offset:
      name: offset
      in: query
      description: The number of items to offset the start of the list from (Pagination)
      required: false
      style: form
      allowReserved: true
      schema:
        type: integer
        format: int32
      example: 0
    limit:
      name: limit
      in: query
      description: Can be used to limit the amount of results returned from a query (Pagination)
      required: false
      style: form
      allowReserved: true
      schema:
        type: integer
        format: int32
      example: 25
  requestBodies:
    UserEnrollRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserEnrollRequest'
    UserSearchRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserSearchRequest'
    UserUpdateRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserUpdateRequest'
    AccountEnrollRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountEnrollRequest'
    AccountSearchRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountSearchRequest'
    AccountUpdateRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountUpdateRequest'
  schemas:
    Account:
      title: Account
      required:
        - accountNumber
        - productCode
        - programEnrollmentCode
      type: object
      properties:
        accountNumber:
          maxLength: 19
          minLength: 0
          type: string
          description: The unique account identifier defined and provided by the client.
          example: '5330333671236516'
        enrollmentDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: 'The date for when the account becomes eligible for rewards program. If undefined, enrollment date is default to the date when Mastercard processes the enrollment.'
          example: '2018-03-11'
        openDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: The date of account opening as defined by the client.
          example: '2017-04-21'
        productCode:
          maxLength: 20
          minLength: 0
          type: string
          description: The account's associated reward product identifier as defined by the client and configured during the implementation of the program.
          example: 7274VCC
        programEnrollmentCode:
          maxLength: 18
          minLength: 0
          type: string
          description: 'The unique identifier for a client''s reward program, defined by the client and configured during implementation.'
          example: ZXSzM
        status:
          maxLength: 20
          minLength: 0
          type: string
          description: Status for the user's account.
          example: NEW
          default: GOOD_STANDING
          enum:
            - CANCELLED
            - GOOD_STANDING
            - INACTIVE
            - NEW
            - ON_HOLD
            - REDEEM_ONLY
    AccountEnrollRequest:
      title: AccountEnrollRequest
      required:
        - accountNumber
        - productCode
        - programEnrollmentCode
        - userNumber
      type: object
      properties:
        accountNumber:
          maxLength: 19
          minLength: 0
          type: string
          description: The unique account identifier defined and provided by the client.
          example: '5330333671236516'
        companyId:
          maxLength: 11
          minLength: 0
          type: string
          description: Mastercard assigned unique identifier for a client.
          example: '611532'
        enrollmentDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: 'The date for when the account becomes eligible for rewards program. If undefined, enrollment date is default to the date when Mastercard processes the enrollment.'
          example: '2018-03-11'
        memberICA:
          type: integer
          description: Interbank Card Association number assigned by Mastercard to the client.
          format: int64
          example: 898923
        openDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: The date of account opening as defined by the client.
          example: '2017-04-21'
        productCode:
          maxLength: 20
          minLength: 0
          type: string
          description: The account's associated reward product identifier as defined by the client and configured during the implementation of the program.
          example: 7274VCC
        programEnrollmentCode:
          maxLength: 18
          minLength: 0
          type: string
          description: 'The unique identifier for a client''s reward program, defined by the client and configured during implementation.'
          example: ZXSzM
        status:
          maxLength: 20
          minLength: 0
          type: string
          description: Status for the user's account.
          example: NEW
          default: GOOD_STANDING
          enum:
            - CANCELLED
            - GOOD_STANDING
            - INACTIVE
            - NEW
            - ON_HOLD
            - REDEEM_ONLY
        userNumber:
          maxLength: 30
          minLength: 0
          type: string
          description: The unique identifier of a user assigned by the client.
          example: C02333333325
    AccountResponse:
      title: AccountResponse
      required:
        - id
      type: object
      properties:
        id:
          maxLength: 50
          minLength: 20
          type: string
          description: Unique Account identifier assigned by Mastercard and provided to client in the account enrollment response.
          example: d8753780-62d1-4775-9549-8ed92c48c290
    AccountSearchRequest:
      title: AccountSearchRequest
      required:
        - accountNumber
      type: object
      properties:
        companyId:
          maxLength: 11
          minLength: 0
          type: string
          description: Mastercard assigned unique identifier for a client.
          example: '611532'
        memberICA:
          type: integer
          description: Interbank Card Association number assigned by Mastercard to the client.
          format: int64
          example: 611532
        accountNumber:
          maxLength: 19
          minLength: 0
          type: string
          description: The unique account identifier defined and provided by the client.
          example: '5330333671236516'
        programEnrollmentCode:
          maxLength: 18
          minLength: 0
          type: string
          description: 'The unique identifier for a client''s reward program, defined by the client and configured during implementation.'
          example: ZXSzM
    AccountSearchResponse:
      title: AccountSearchResponse
      required:
        - accountNumber
        - productCode
        - programEnrollmentCode
      type: object
      properties:
        accountNumber:
          maxLength: 19
          minLength: 0
          type: string
          description: The unique account identifier defined and provided by the client.
          example: '5330333671236516'
        companyId:
          maxLength: 11
          minLength: 0
          type: string
          description: Mastercard assigned unique identifier for a client.
          example: '611532'
        enrollmentDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: 'The date for when the account becomes eligible for rewards program. If undefined, enrollment date is default to the date when Mastercard processes the enrollment.'
          example: '2018-03-11'
        id:
          maxLength: 50
          minLength: 20
          type: string
          description: Unique Account identifier assigned by Mastercard and provided to client in the account enrollment response.
          example: d8753780-62d1-4775-9549-8ed92c48c290
        memberICA:
          type: integer
          description: Interbank Card Association number assigned by Mastercard to the client.
          format: int64
          example: 898923
        openDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: The date of account opening as defined by the client.
          example: '2017-04-21'
        productCode:
          maxLength: 20
          minLength: 0
          type: string
          description: The account's associated reward product identifier as defined by the client and configured during the implementation of the program.
          example: 7274VCC
        programEnrollmentCode:
          maxLength: 18
          minLength: 0
          type: string
          description: 'The unique identifier for a client''s reward program, defined by the client and configured during implementation.'
          example: ZXSzM
        status:
          maxLength: 20
          minLength: 0
          type: string
          description: Status for the user's account.
          example: NEW
        userNumber:
          maxLength: 30
          minLength: 0
          type: string
          description: The unique identifier of a user assigned by the client.
          example: C02333333325
    AccountUpdateRequest:
      title: AccountUpdateRequest
      required:
        - status
      type: object
      properties:
        companyId:
          maxLength: 11
          minLength: 0
          type: string
          description: Mastercard assigned unique identifier for a client.
          example: '611532'
        memberICA:
          type: integer
          description: Interbank Card Association number assigned by Mastercard to the client.
          format: int64
          example: 898923
        status:
          maxLength: 20
          minLength: 0
          type: string
          description: Status for the user's account
          example: NEW
          enum:
            - CANCELLED
            - GOOD_STANDING
            - INACTIVE
            - NEW
            - ON_HOLD
            - REDEEM_ONLY
    Error:
      title: Error
      type: object
      properties:
        Source:
          maxLength: 50
          minLength: 10
          type: string
          description: Source of the error
          example: Loyalty-Enrollment
        ReasonCode:
          maxLength: 100
          minLength: 10
          type: string
          description: A unique constant identifying the error case encountered during transaction processing.
          example: A unique error constant
        Description:
          maxLength: 100
          minLength: 1
          type: string
          description: Short description of the ReasonCode field.
          example: Short description of validation or service error message
        Recoverable:
          type: boolean
          description: 'Indicates whether this error will always be returned for this request, or retrying could change the outcome.'
          example: false
        Details:
          maxLength: 100
          minLength: 0
          type: string
          description: 'Where appropriate, indicates detailed information about data received.'
          example: Detailed information about data received.
    ErrorList:
      title: ErrorList
      required:
        - Error
      type: object
      properties:
        Error:
          minItems: 1
          type: array
          description: The list of error messages
          items:
            $ref: '#/components/schemas/Error'
    Errors:
      title: Errors
      required:
        - Errors
      type: object
      properties:
        Errors:
          $ref: '#/components/schemas/ErrorList'
    PagedResponseOfAccountSearchResponse:
      title: PagedResponseOfAccountSearchResponse
      type: object
      properties:
        count:
          type: integer
          description: The number of items that are in this offset batch
          format: int32
          example: 1
        offset:
          type: integer
          description: The number of items to offset the start of the list from
          format: int32
          example: 0
        limit:
          type: integer
          description: The number of items in the list to be limited to
          format: int32
          example: 25
        total:
          type: integer
          description: The total number of items that are in the entire collection
          format: int64
          example: 1
        items:
          minItems: 0
          type: array
          description: The list of Accounts that are in the entire collection
          items:
            $ref: '#/components/schemas/AccountSearchResponse'
    PagedResponseOfUserSearchResponse:
      title: PagedResponseOfUserSearchResponse
      type: object
      properties:
        count:
          type: integer
          description: The number of items that are in this offset batch
          format: int32
          example: 1
        offset:
          type: integer
          description: The number of items to offset the start of the list from
          format: int32
          example: 0
        limit:
          type: integer
          description: The number of items in the list to be limited to
          format: int32
          example: 25
        total:
          type: integer
          description: The total number of items that are in the entire collection
          format: int64
          example: 1
        items:
          minItems: 0
          type: array
          description: The list of Users that are in the entire collection
          items:
            $ref: '#/components/schemas/UserSearchResponse'
    UserAddress:
      title: UserAddress
      type: object
      properties:
        addressLine1:
          maxLength: 80
          minLength: 0
          pattern: '^$|^[ ,.:&_\)\(\[\]\-\n\t\\\/\p{L}\p{M}\p{N}\p{Z}]+$'
          type: string
          description: Address Line 1 of the User's address
          example: 10 Upper Bank Street
        addressLine2:
          maxLength: 80
          minLength: 0
          pattern: '^$|^[ ,.:&_\)\(\[\]\-\n\t\\\/\p{L}\p{M}\p{N}\p{Z}]+$'
          type: string
          description: Address Line 2 of the User's address
          example: Chesterfield
        addressLine3:
          maxLength: 80
          minLength: 0
          pattern: '^$|^[ ,.:&_\)\(\[\]\-\n\t\\\/\p{L}\p{M}\p{N}\p{Z}]+$'
          type: string
          description: Address Line 3 of the User's address
          example: Canary Wharf
        addressLine4:
          maxLength: 80
          minLength: 0
          pattern: '^$|^[ ,.:&_\)\(\[\]\-\n\t\\\/\p{L}\p{M}\p{N}\p{Z}]+$'
          type: string
          description: Address Line 4 of the User's address
          example: Tower Hamlets
        city:
          maxLength: 30
          minLength: 0
          pattern: '^[\.\p{L}\p{Z}]*$'
          type: string
          description: City name as per User's address
          example: London
        countryCode:
          maxLength: 3
          minLength: 2
          pattern: '^[\p{L}]*$'
          type: string
          description: Country Code as per User's address
          example: ENG
        postalCode:
          maxLength: 14
          minLength: 0
          pattern: '^$|^[ ,.:_\p{L}\p{N}]+$'
          type: string
          description: Postal Code as per the User's address
          example: E1 6AN
        stateProvinceCode:
          maxLength: 3
          minLength: 2
          pattern: '^[\p{L}]*$'
          type: string
          description: State Code as per the User's address
          example: JS
    UserEnrollRequest:
      title: UserEnrollRequest
      required:
        - userNumber
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Account'
        address:
          $ref: '#/components/schemas/UserAddress'
        birthDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: User's date of birth
          example: '1975-03-11'
        businessPhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's business phone number
          example: +1(0)1234567890
        companyId:
          maxLength: 11
          minLength: 0
          type: string
          description: Mastercard assigned unique identifier for a client.
          example: '611532'
        emailAddress:
          maxLength: 120
          minLength: 0
          type: string
          description: User's email address
          example: john.smith@mastercard.com
        employee:
          type: boolean
          description: Used to assign Employee status to a user
          example: false
          default: false
        firstName:
          maxLength: 50
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's first name
          example: John
        gender:
          maxLength: 1
          minLength: 0
          type: string
          description: The ISO code used to determine the gender of the User
          example: '1'
          enum:
            - '0'
            - '1'
            - '2'
            - '9'
        homePhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's home phone number
          example: +1(0)1234567892
        lastName:
          maxLength: 50
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's last name
          example: Smith
        memberICA:
          type: integer
          description: Interbank Card Association number assigned by Mastercard to the client.
          format: int64
          example: 898923
        mobilePhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's mobile phone number
          example: +1(0)1234567891
        motherMaidenName:
          maxLength: 30
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's mother maiden name
          example: Jennifer
        nationalIdentifier:
          maxLength: 50
          minLength: 0
          type: string
          description: 'User''s unique identifier assigned by the national or government system. For example, passport number or tax identification number'
          example: 324-56-7574
        userNumber:
          maxLength: 30
          minLength: 0
          type: string
          description: The unique identifier of a user assigned by the client
          example: C02333333325
        vip:
          type: boolean
          description: Used to assign VIP status to a user
          example: true
          default: false
    UserEnrollResponse:
      title: UserEnrollResponse
      type: object
      properties:
        id:
          maxLength: 50
          minLength: 20
          type: string
          description: Unique User identifier assigned by Mastercard and provided to client at the time of user enrollment response.
          example: 2a53135b-c1f2-4cec-88a9-b0941304d9d7
        account:
          $ref: '#/components/schemas/AccountResponse'
    UserSearchRequest:
      title: UserSearchRequest
      required:
        - userNumber
      type: object
      properties:
        companyId:
          maxLength: 11
          minLength: 0
          type: string
          description: Mastercard assigned unique identifier for a client.
          example: '611532'
        memberICA:
          type: integer
          description: Interbank Card Association number assigned by Mastercard to the client.
          format: int64
          example: 898923
        userNumber:
          maxLength: 30
          minLength: 0
          type: string
          description: The unique identifier of a user assigned by the client
          example: C02333333325
    UserSearchResponse:
      title: UserSearchResponse
      type: object
      properties:
        address:
          $ref: '#/components/schemas/UserAddress'
        birthDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: User's date of birth
          example: '1975-03-11'
        businessPhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's business phone number
          example: +1(0)1234567890
        companyId:
          maxLength: 11
          minLength: 0
          type: string
          description: Mastercard assigned unique identifier for a client.
          example: '611532'
        emailAddress:
          maxLength: 120
          minLength: 0
          type: string
          description: User's email address
          example: john.smith@mastercard.com
        employee:
          type: boolean
          description: Used to assign Employee status to a user
          example: false
          default: false
        firstName:
          maxLength: 50
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's first name
          example: John
        gender:
          maxLength: 1
          minLength: 0
          type: string
          description: The ISO code used to determine the gender of the User
          example: '1'
        homePhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's home phone number
          example: +1(0)1234567892
        id:
          maxLength: 50
          minLength: 20
          type: string
          description: Unique User identifier assigned by Mastercard and provided to client at the time of user enrollment response.
          example: 2a53135b-c1f2-4cec-88a9-b0941304d9d7
        lastName:
          maxLength: 50
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's last name
          example: Smith
        memberICA:
          type: integer
          description: Interbank Card Association number assigned by Mastercard to the client.
          format: int64
          example: 898923
        mobilePhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's mobile phone number
          example: +1(0)1234567891
        motherMaidenName:
          maxLength: 30
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's mother maiden name
          example: Jennifer
        nationalIdentifier:
          maxLength: 50
          minLength: 0
          type: string
          description: 'User''s unique identifier assigned by the national or government system. For example, passport number or tax identification number'
          example: 324-56-7574
        userNumber:
          maxLength: 30
          minLength: 0
          type: string
          description: User type identifier assigned by the Issuer to the customer.
          example: C02333333325
        vip:
          type: boolean
          description: Used to assign VIP status to a user
          example: true
          default: false
    UserUpdateRequest:
      title: UserUpdateRequest
      type: object
      properties:
        address:
          $ref: '#/components/schemas/UserAddress'
        birthDate:
          maxLength: 10
          minLength: 0
          type: string
          format: date
          description: User's date of birth
          example: '1975-03-11'
        businessPhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's business phone number
          example: +1(0)1234567890
        companyId:
          maxLength: 11
          minLength: 0
          type: string
          description: Mastercard assigned unique identifier for a client.
          example: '611532'
        emailAddress:
          maxLength: 120
          minLength: 0
          type: string
          description: User's email address
          example: john.smith@mastercard.com
        employee:
          type: boolean
          description: Used to assign Employee status to a user
          example: false
          default: false
        firstName:
          maxLength: 50
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's first name
          example: John
        gender:
          maxLength: 1
          minLength: 0
          type: string
          description: The ISO code used to determine the gender of the User
          example: '1'
          enum:
            - '0'
            - '1'
            - '2'
            - '9'
        homePhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's home phone number
          example: +1(0)1234567892
        lastName:
          maxLength: 50
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's last name
          example: Smith
        memberICA:
          type: integer
          description: Interbank Card Association number assigned by Mastercard to the client.
          format: int64
          example: 898923
        mobilePhoneNumber:
          maxLength: 25
          minLength: 0
          pattern: '^$|^[\ \+\-\(\)\p{N}]*$'
          type: string
          description: User's mobile phone number
          example: +1(0)1234567891
        motherMaidenName:
          maxLength: 30
          minLength: 0
          pattern: '^[\.\-\p{L}\p{M}\p{N}\p{Z}]*$'
          type: string
          description: User's mother maiden name
          example: Jennifer
        nationalIdentifier:
          maxLength: 50
          minLength: 0
          type: string
          description: 'User''s unique identifier assigned by the national or government system. For example, passport number or tax identification number'
          example: 324-56-7574
        vip:
          type: boolean
          description: Used to assign VIP status to a user
          example: true
          default: false
    UserUpdateResponse:
      title: UserUpdateResponse
      type: object
      properties:
        id:
          maxLength: 50
          minLength: 20
          type: string
          description: Unique User identifier assigned by Mastercard and provided to client at the time of user enrollment response.
          example: 2a53135b-c1f2-4cec-88a9-b0941304d9d7
  responses:
    EnrollUserSuccessfully:
      description: Successfully Enrolled User
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserEnrollResponse'
    SearchUserSuccessfully:
      description: Successfully Retrieved User(s)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagedResponseOfUserSearchResponse'
    FindUserSuccessfully:
      description: Successfully Retrieved User
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserSearchResponse'
    UpdateUserSuccessfully:
      description: Successfully Updated User
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserUpdateResponse'
    EnrollAccountSuccessfully:
      description: Successfully Enrolled Account
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountResponse'
    SearchAccountSuccessfully:
      description: Successfully Retrieved Account(s)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagedResponseOfAccountSearchResponse'
    FindAccountSuccessfully:
      description: Successfully Retrieved Account
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountSearchResponse'
    UpdateAccountSuccessfully:
      description: Successfully Updated Account
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountResponse'
    EnrollUserInvalidRequest:
      description: Enroll UserInvalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            INVALID_REQUEST:
              $ref: '#/components/examples/EnrollUserInvalidRequest'
    SearchUserInvalidRequest:
      description: Search User Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            INVALID_REQUEST:
              $ref: '#/components/examples/SearchUserInvalidRequest'
    UserNotFound:
      description: User Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            RESOURCE_NOT_FOUND:
              $ref: '#/components/examples/UserNotFound'
    UpdateUserInvalidRequest:
      description: Update User Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            INVALID_REQUEST:
              $ref: '#/components/examples/UpdateUserInvalidRequest'
    EnrollAccountInvalidRequest:
      description: Enroll Account Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            INVALID_REQUEST:
              $ref: '#/components/examples/EnrollAccountInvalidRequest'
    SearchAccountInvalidRequest:
      description: Search Account Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            INVALID_REQUEST:
              $ref: '#/components/examples/SearchAccountInvalidRequest'
    AccountNotFound:
      description: Account Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            RESOURCE_NOT_FOUND:
              $ref: '#/components/examples/AccountNotFound'
    UpdateAccountInvalidRequest:
      description: Update Account Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            INVALID_REQUEST:
              $ref: '#/components/examples/UpdateAccountInvalidRequest'
    Unauthorized:
      description: Client could not be authorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          examples:
            AUTHORIZATION_ERROR:
              $ref: '#/components/examples/Unauthorized'
  examples:
    EnrollUserInvalidRequest:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: INVALID_FIELD_FORMAT_FIRST_NAME
              Description: First Name must be alphanumeric.
              Recoverable: false
              Details: null
    SearchUserInvalidRequest:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: MISSING_REQUIRED_FIELD_USER_NUMBER
              Description: User Number is required.
              Recoverable: false
              Details: null
    UserNotFound:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: INVALID_FIELD_VALUE_USER_ID
              Description: User ID could not be found.
              Recoverable: false
              Details: null
    UpdateUserInvalidRequest:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: INVALID_FIELD_VALUE_COMPANY_ID
              Description: Company ID does not exists.
              Recoverable: false
              Details: null
    EnrollAccountInvalidRequest:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: MISSING_REQUIRED_FIELD_ACCOUNT_NUMBER
              Description: Account Number is required.
              Recoverable: false
              Details: null
    SearchAccountInvalidRequest:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: MISSING_REQUIRED_FIELD_ACCOUNT_NUMBER
              Description: Account Number is required.
              Recoverable: false
              Details: null
    AccountNotFound:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: INVALID_FIELD_VALUE_ACCOUNT_ID
              Description: Account ID could not be found.
              Recoverable: false
              Details: null
    UpdateAccountInvalidRequest:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: MISSING_REQUIRED_FIELD_STATUS
              Description: Status is required.
              Recoverable: false
              Details: null
    Unauthorized:
      value:
        Errors:
          Error:
            - Source: Loyalty-Enrollment
              ReasonCode: AUTHORIZATION_ERROR
              Description: Client could not be authorized.
              Recoverable: true
              Details: null